# Generated by Django 4.0.2 on 2022-03-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
