# Generated by Django 4.0.2 on 2022-03-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinationapp', '0002_places_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='travelblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_img', models.ImageField(upload_to='blog_image')),
                ('blog_desc', models.TextField()),
            ],
        ),
    ]
